chore: cosmetic changes in husky log pre-push hook

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,11 +1,19 @@
 #!/bin/bash
-echo "⏳ Generating types..."
+
+echo "🚀 Checking before pushing..."
+
+echo ""
+echo "⏳ Generating project types..."
 pnpm next typegen
 
+echo ""
 echo "⏳ Type-checking..."
-pnpm type-check || { echo "❌ Type errors. Push aborted."; exit 1; }
+pnpm type-check || { echo ""; echo "❌ Type errors. Push aborted."; exit 1; }
 
+echo ""
 echo "⏳ Linting..."
-pnpm lint || { echo "❌ Lint errors. Push aborted."; exit 1; }
+pnpm lint || { echo ""; echo "❌ Lint errors. Push aborted."; exit 1; }
 
-echo "✅ All checks passed."
+echo ""
+echo "✅ All checks passed. Pushing..."
+echo ""
